### PR TITLE
Update to 0.4.4 and rerendered

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This looks good to me. I will merge when all the CIs are green.

**Comment by melund** [comment]
@ccordoba12 This is needed for spyder 3.2.1 to install... Otherwise I get: 

```
(Anaconda3) mel@ANYBODY-MEL2 ~\Documents\GitHub $ conda install spyder=3.1.2
Fetching package metadata .......
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current win-64 channels:
  - spyder 3.1.2* -> qtawesome >=0.4.1

You can search for packages on anaconda.org with

    anaconda search -t conda qtawesome

```

**Comment by melund** [comment]
@SylvainCorlay ... Great...

**Comment by SylvainCorlay** [comment]
The travis ci build failed due to an issue downloading miniconda. Restarted it.

**Comment by melund** [comment]
It think it did it again. I will make a new push to restart it.

**Comment by melund** [comment]
@conda-forge/core We are having some issues with mac builds on Travis. 

Any clue to what is going on?

```
bash: Miniconda3-latest-MacOSX-x86_64.sh: No such file or directory
/Users/travis/build.sh: line 62: /Users/travis/miniconda3/bin/activate: No such file or directory
/Users/travis/build.sh: line 63: conda: command not found
/Users/travis/build.sh: line 64: conda: command not found
/Users/travis/build.sh: line 65: conda: command not found
/Users/travis/build.sh: line 66: run_conda_forge_build_setup: No such file or directory
The command "MINICONDA_URL="http://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
  
  source /Users/travis/miniconda3/bin/activate root
  conda config --add channels conda-forge
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
  " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by ocefpaf** [comment]
You need to rerender. Do you have conda-smithy installed?

**Comment by melund** [comment]
@ocefpaf . I did rerender with the newest conda-smithy yesterday. I will try again.

**Comment by melund** [comment]
Ahh. I see it did something new today.

**Comment by melund** [comment]
@conda-forge/qtawesome It is ready to be merged

**Comment by ccordoba12** [comment]
Ok, thanks a lot @melund!

**Pull request merged**
